// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABKXHQwatZBdhlTx0PjB5yI-KZBf74-pw',
    appId: '1:752550302844:web:b7a73ea095e0c0ffa325f9',
    messagingSenderId: '752550302844',
    projectId: 'dropnote-4330',
    authDomain: 'dropnote-4330.firebaseapp.com',
    storageBucket: 'dropnote-4330.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5x3y2ksR6kToR3C1TzJpY9XJ0wwoHAqw',
    appId: '1:752550302844:android:242fe7a2d2d555c4a325f9',
    messagingSenderId: '752550302844',
    projectId: 'dropnote-4330',
    storageBucket: 'dropnote-4330.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDhPl6_RalNcPTZhtE3MA2ItwQV7ET4Yc',
    appId: '1:752550302844:ios:d5a7bf692a8838a2a325f9',
    messagingSenderId: '752550302844',
    projectId: 'dropnote-4330',
    storageBucket: 'dropnote-4330.appspot.com',
    iosClientId: '752550302844-5hhjaeesfut4aveinp3p286dfu14rtle.apps.googleusercontent.com',
    iosBundleId: 'com.example.dropnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDhPl6_RalNcPTZhtE3MA2ItwQV7ET4Yc',
    appId: '1:752550302844:ios:d5a7bf692a8838a2a325f9',
    messagingSenderId: '752550302844',
    projectId: 'dropnote-4330',
    storageBucket: 'dropnote-4330.appspot.com',
    iosClientId: '752550302844-5hhjaeesfut4aveinp3p286dfu14rtle.apps.googleusercontent.com',
    iosBundleId: 'com.example.dropnote',
  );
}
